### ISSUE TITLE
Facing issues with `import simplejson`

### ISSUE THREAD

**Issue by ktaragorn** [nkanand4/plugin.video.indopia#2]
Plugin not starting. Simplejson seems to be installed as an addon but it is not getting imported. This is on android box kodi 15
Error at https://goo.gl/photos/3cYj8yRvHPKPievs6

**Comment by ktaragorn** [comment]
Do you need to add `simplejson` as a dependency in ur `.xml`?

**Comment by nkanand4** [comment]
This was written for the older version of Kodi, but yes for the newer versions, we need to add <import addon="script.module.simplejson" /> to our addon.xml. Please let me know if you can add and package it yourself otherwise I will release another version coming weekend. Thanks.

**Comment by ktaragorn** [comment]
I wont have the time before this weekend and i dont have the experience needed either.. Just trying to get into addon writing..

**Comment by nkanand4** [comment]
All right, then I will fix and test it with newer version of Kodi and release one this weekend. Thanks for reporting.

**Comment by ktaragorn** [comment]
Great, Thanks! will be sure to check it out

**Comment by ktaragorn** [comment]
I have free time now, I will try to fix and PR

**Comment by nkanand4** [comment]
I have copied over your changes after testing into the older versions of kodi/xbmc.
